#!/usr/bin/env node
// sync-core.mjs — build core/shuiyuan_core.mjs from vendor/shuiyuan_discourse.mjs
// (the read-only CLI, vendored verbatim in this repo). The vendored file is NEVER
// modified; the generated copy is gitignored and regenerated on demand.
//
// Differences from a plain copy (the CLI stays a runnable Node script):
//   1. shebang stripped (the copy is imported as a library);
//   2. the seven node: builtin imports are remapped to ./shims/*.mjs so the
//      same code runs in a Manifest V3 service worker;
//   3. shims/buffer.mjs is imported for side effects (installs globalThis.Buffer);
//   4. an export block is appended (unless the source exports `execute` itself).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
// Single source of truth: the vendored copy in this repo. Nothing outside the
// extension directory is read, so a fresh clone always builds identically.
const SRC = path.resolve(HERE, "vendor/shuiyuan_discourse.mjs");
const OUT = path.resolve(HERE, "core/shuiyuan_core.mjs");

if (!fs.existsSync(SRC)) {
  console.error(`sync-core: missing ${path.relative(HERE, SRC)} — the repo is incomplete.`);
  process.exit(1);
}

// Every symbol the service worker imports from the core copy. The guard fails
// loudly (exit 1) if the vendored CLI stops matching, instead of silently
// copying an incompatible version.
const REQUIRED_SYMBOLS = [
  ["execute", /async function execute\(/],
  ["normalizeSite", /function normalizeSite\(/],
  ["resolvePath", /function resolvePath\(/],
  ["normalizeRateLimitPayload", /function normalizeRateLimitPayload\(/],
  ["SkillError", /class SkillError\b/],
  ["ReadOnlyViolation", /class ReadOnlyViolation\b/],
  ["CredentialError", /class CredentialError\b/],
  ["HttpRequestError", /class HttpRequestError\b/],
  ["DEFAULT_SITE", /const DEFAULT_SITE\b/],
  ["DEFAULT_TIMEOUT", /const DEFAULT_TIMEOUT\b/],
  ["DEFAULT_AUTH_PATH", /const DEFAULT_AUTH_PATH\b/],
  ["DEFAULT_AUTH_PENDING_PATH", /const DEFAULT_AUTH_PENDING_PATH\b/],
  ["DEFAULT_ROTATION_STATE_PATH", /const DEFAULT_ROTATION_STATE_PATH\b/],
  ["DEFAULT_IMAGE_CACHE_DIR", /const DEFAULT_IMAGE_CACHE_DIR\b/],
];

// Verbatim import-line remaps. Exact-match on purpose: if the vendored CLI
// reformats its imports we fail loudly here rather than ship a half-remapped file.
const IMPORT_REMAPS = [
  ['import fs from "node:fs";', 'import fs from "../shims/fs.mjs";'],
  ['import os from "node:os";', 'import os from "../shims/os.mjs";'],
  ['import path from "node:path";', 'import path from "../shims/path.mjs";'],
  ['import process from "node:process";', 'import process from "../shims/process.mjs";'],
  [
    'import { spawnSync } from "node:child_process";',
    'import { spawnSync } from "../shims/child_process.mjs";',
  ],
  [
    'import { constants, createHash, generateKeyPairSync, privateDecrypt, randomBytes, randomUUID } from "node:crypto";',
    'import { constants, createHash, generateKeyPairSync, privateDecrypt, randomBytes, randomUUID } from "../shims/crypto.mjs";',
  ],
  ['import { pathToFileURL } from "node:url";', 'import { pathToFileURL } from "../shims/node_url.mjs";'],
];

const BUFFER_SIDE_EFFECT_IMPORT = 'import "../shims/buffer.mjs";';

const HEADER =
  "// GENERATED by sync-core.mjs from vendor/shuiyuan_discourse.mjs — do not edit.\n";

const EXPORT_BLOCK = `
// === Appended by sync-core.mjs (not part of the vendored CLI) ===
export {
  execute,
  normalizeSite,
  resolvePath,
  normalizeRateLimitPayload,
  SkillError,
  ReadOnlyViolation,
  CredentialError,
  HttpRequestError,
  DEFAULT_SITE,
  DEFAULT_TIMEOUT,
  DEFAULT_AUTH_PATH,
  DEFAULT_AUTH_PENDING_PATH,
  DEFAULT_ROTATION_STATE_PATH,
  DEFAULT_IMAGE_CACHE_DIR,
};
`;

function main() {
  const stat = fs.statSync(SRC); // throws with a clear message if missing
  let source = fs.readFileSync(SRC, "utf8").replace(/^#!.*\n/, "");

  const missing = REQUIRED_SYMBOLS.filter(([, re]) => !re.test(source)).map(([name]) => name);
  if (missing.length > 0) {
    console.error(`sync-core: source ${SRC} is missing required symbols:`);
    for (const name of missing) console.error(`  - ${name}`);
    console.error("sync-core: the vendored CLI structure changed; update the export list above.");
    process.exit(1);
  }

  for (const [from, to] of IMPORT_REMAPS) {
    if (!source.includes(from)) {
      console.error(`sync-core: expected import line not found in ${SRC}:`);
      console.error(`  ${from}`);
      console.error("sync-core: vendored CLI imports changed; update IMPORT_REMAPS.");
      process.exit(1);
    }
    source = source.replace(from, to);
  }
  // Install the Buffer global before the core body uses it. Anchor on the last
  // import remap (node:url) so the injection sits with the other imports.
  source = source.replace(
    IMPORT_REMAPS[IMPORT_REMAPS.length - 1][1],
    `${IMPORT_REMAPS[IMPORT_REMAPS.length - 1][1]}\n${BUFFER_SIDE_EFFECT_IMPORT}`,
  );

  // Dedup guard: if the vendored file ever starts exporting `execute` itself,
  // appending our block would be an ESM duplicate-export early error.
  const alreadyExportsExecute = /export\s*\{[^}]*\bexecute\b/s.test(source);
  const body = alreadyExportsExecute ? source : source.replace(/\s*$/, "\n") + EXPORT_BLOCK;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, HEADER + body, "utf8");

  console.log(`sync-core: ${SRC}`);
  console.log(`  mtime: ${stat.mtime.toISOString()}, ${stat.size} bytes`);
  console.log(
    `  -> ${OUT} (imports remapped, export block ${alreadyExportsExecute ? "already present, skipped" : "appended"})`,
  );
}

main();
